# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from models.xapi_agent_group import XapiAgentGroup  # noqa: E501
from rustici_engine.rest import ApiException


class TestXapiAgentGroup(unittest.TestCase):
    """XapiAgentGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testXapiAgentGroup(self):
        """Test XapiAgentGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rustici_engine.models.xapi_agent_group.XapiAgentGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
