# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.dispatch_registration_count_schema import DispatchRegistrationCountSchema  # noqa: E501
from swagger_client.rest import ApiException


class TestDispatchRegistrationCountSchema(unittest.TestCase):
    """DispatchRegistrationCountSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDispatchRegistrationCountSchema(self):
        """Test DispatchRegistrationCountSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dispatch_registration_count_schema.DispatchRegistrationCountSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
