# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from models.credential_list_schema import CredentialListSchema  # noqa: E501
from rustici_engine.rest import ApiException


class TestCredentialListSchema(unittest.TestCase):
    """CredentialListSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredentialListSchema(self):
        """Test CredentialListSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rustici_engine.models.credential_list_schema.CredentialListSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
