# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from models.reporting_plugin_schema import ReportingPluginSchema  # noqa: E501
from rustici_engine.rest import ApiException


class TestReportingPluginSchema(unittest.TestCase):
    """ReportingPluginSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportingPluginSchema(self):
        """Test ReportingPluginSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rustici_engine.models.reporting_plugin_schema.ReportingPluginSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
