# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from models.import_connector_request_schema import ImportConnectorRequestSchema  # noqa: E501
from rustici_engine.rest import ApiException


class TestImportConnectorRequestSchema(unittest.TestCase):
    """ImportConnectorRequestSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImportConnectorRequestSchema(self):
        """Test ImportConnectorRequestSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rustici_engine.models.import_connector_request_schema.ImportConnectorRequestSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
