# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from models.create_registration_schema import CreateRegistrationSchema  # noqa: E501
from rustici_engine.rest import ApiException


class TestCreateRegistrationSchema(unittest.TestCase):
    """CreateRegistrationSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateRegistrationSchema(self):
        """Test CreateRegistrationSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rustici_engine.models.create_registration_schema.CreateRegistrationSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
