# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.about_api import AboutApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAboutApi(unittest.TestCase):
    """AboutApi unit test stubs"""

    def setUp(self):
        self.api = api.about_api.AboutApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_about(self):
        """Test case for get_about

        Get back the version and platform of the running instance of Engine  # noqa: E501
        """
        pass

    def test_get_user_count(self):
        """Test case for get_user_count

        Gets the number of users for the specified tenant or across all tenants when none is specified  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
