# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from api.course_api import CourseApi  # noqa: E501
from rustici_engine.rest import ApiException


class TestCourseApi(unittest.TestCase):
    """CourseApi unit test stubs"""

    def setUp(self):
        self.api = api.course_api.CourseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_build_course_preview_launch_link(self):
        """Test case for build_course_preview_launch_link

        Returns the link to use to preview this course  # noqa: E501
        """
        pass

    def test_build_course_preview_launch_link_with_version(self):
        """Test case for build_course_preview_launch_link_with_version

        Returns the link to use to preview this course  # noqa: E501
        """
        pass

    def test_create_fetch_and_import_course_job(self):
        """Test case for create_fetch_and_import_course_job

        Start a job to fetch and import a course.  # noqa: E501
        """
        pass

    def test_create_upload_and_import_course_job(self):
        """Test case for create_upload_and_import_course_job

        Upload a course and start an import job for it.  # noqa: E501
        """
        pass

    def test_delete_course(self):
        """Test case for delete_course

        Delete `courseId`  # noqa: E501
        """
        pass

    def test_delete_course_configuration_setting(self):
        """Test case for delete_course_configuration_setting

        Clears the `settingId` value for this course  # noqa: E501
        """
        pass

    def test_delete_course_version(self):
        """Test case for delete_course_version

        Delete version `versionId` of `courseId`  # noqa: E501
        """
        pass

    def test_delete_course_version_configuration_setting(self):
        """Test case for delete_course_version_configuration_setting

        Clears the `settingId` value for this course and version.  # noqa: E501
        """
        pass

    def test_get_course(self):
        """Test case for get_course

        Get information about `courseId`  # noqa: E501
        """
        pass

    def test_get_course_configuration(self):
        """Test case for get_course_configuration

        Returns all configuration settings for this course  # noqa: E501
        """
        pass

    def test_get_course_statements(self):
        """Test case for get_course_statements

        Get xAPI statements for `courseId`  # noqa: E501
        """
        pass

    def test_get_course_version_configuration(self):
        """Test case for get_course_version_configuration

        Returns all configuration settings for this course and version.  # noqa: E501
        """
        pass

    def test_get_course_version_info(self):
        """Test case for get_course_version_info

        Get version `versionId` of `courseId`  # noqa: E501
        """
        pass

    def test_get_course_version_statements(self):
        """Test case for get_course_version_statements

        Get xAPI statements for version `versionId` of `courseId`  # noqa: E501
        """
        pass

    def test_get_course_versions(self):
        """Test case for get_course_versions

        Get all versions of `courseId`  # noqa: E501
        """
        pass

    def test_get_courses(self):
        """Test case for get_courses

        Get a list of all courses for the specified tenant  # noqa: E501
        """
        pass

    def test_get_import_job_status(self):
        """Test case for get_import_job_status

        Check the status of an import job.  # noqa: E501
        """
        pass

    def test_import_course_without_upload(self):
        """Test case for import_course_without_upload

        Create a course  # noqa: E501
        """
        pass

    def test_set_course_configuration(self):
        """Test case for set_course_configuration

        Set configuration settings for this course.  # noqa: E501
        """
        pass

    def test_set_course_title(self):
        """Test case for set_course_title

        Sets the course title for `courseId`  # noqa: E501
        """
        pass

    def test_set_course_version_configuration(self):
        """Test case for set_course_version_configuration

        Set configuration settings for this course and version.  # noqa: E501
        """
        pass

    def test_upload_and_import_course(self):
        """Test case for upload_and_import_course

        Upload a course to import  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
