# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from api.xapi_api import XapiApi  # noqa: E501
from rustici_engine.rest import ApiException


class TestXapiApi(unittest.TestCase):
    """XapiApi unit test stubs"""

    def setUp(self):
        self.api = api.xapi_api.XapiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_statement_pipe(self):
        """Test case for create_statement_pipe

        Create an xAPI statement pipe.  # noqa: E501
        """
        pass

    def test_create_xapi_credential(self):
        """Test case for create_xapi_credential

        Create an xAPI credential  # noqa: E501
        """
        pass

    def test_delete_statement_pipe(self):
        """Test case for delete_statement_pipe

        Deletes the xAPI statement pipe specified with the id `statementPipeId`  # noqa: E501
        """
        pass

    def test_delete_xapi_credential(self):
        """Test case for delete_xapi_credential

        Deletes the xAPI credential specified with the id `xapiCredentialId`  # noqa: E501
        """
        pass

    def test_get_statement_pipe(self):
        """Test case for get_statement_pipe

        Retrieves xAPI statement pipe specified by id `statementPipeId.`  # noqa: E501
        """
        pass

    def test_get_statement_pipes(self):
        """Test case for get_statement_pipes

        Get a list of all xAPI statement pipes  # noqa: E501
        """
        pass

    def test_get_xapi_credential(self):
        """Test case for get_xapi_credential

        Retrieves the xAPI credential specified by id `xapiCredentialId`  # noqa: E501
        """
        pass

    def test_get_xapi_credentials(self):
        """Test case for get_xapi_credentials

        Get a list of all xAPI credentials  # noqa: E501
        """
        pass

    def test_set_statement_pipe(self):
        """Test case for set_statement_pipe

        Either edits an existing xAPI statement pipe or creates a new one, specified by id `statementPipeId`  # noqa: E501
        """
        pass

    def test_set_xapi_credential(self):
        """Test case for set_xapi_credential

        Either edits an existing xAPI credential or creates a new one, specified by id `xapiCredentialId`  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
