# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from models.settings_individual_schema import SettingsIndividualSchema  # noqa: E501
from rustici_engine.rest import ApiException


class TestSettingsIndividualSchema(unittest.TestCase):
    """SettingsIndividualSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSettingsIndividualSchema(self):
        """Test SettingsIndividualSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rustici_engine.models.settings_individual_schema.SettingsIndividualSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
