# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from models.destination_id_schema import DestinationIdSchema  # noqa: E501
from rustici_engine.rest import ApiException


class TestDestinationIdSchema(unittest.TestCase):
    """DestinationIdSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDestinationIdSchema(self):
        """Test DestinationIdSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rustici_engine.models.destination_id_schema.DestinationIdSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
