# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from api.content_connectors_api import ContentConnectorsApi  # noqa: E501
from rustici_engine.rest import ApiException


class TestContentConnectorsApi(unittest.TestCase):
    """ContentConnectorsApi unit test stubs"""

    def setUp(self):
        self.api = api.content_connectors_api.ContentConnectorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_connector(self):
        """Test case for create_connector

        Create a connector  # noqa: E501
        """
        pass

    def test_get_connector_content_list(self):
        """Test case for get_connector_content_list

        Get list of available content  # noqa: E501
        """
        pass

    def test_get_connectors_list(self):
        """Test case for get_connectors_list

        Get content connectors  # noqa: E501
        """
        pass

    def test_get_refresh_job_status(self):
        """Test case for get_refresh_job_status

        Check the status of a refresh job.  # noqa: E501
        """
        pass

    def test_refresh_connector_content_list_job(self):
        """Test case for refresh_connector_content_list_job

        Start a job to refresh the list of available content  # noqa: E501
        """
        pass

    def test_search_remote_connector_content(self):
        """Test case for search_remote_connector_content

        search remote content  # noqa: E501
        """
        pass

    def test_update_connector(self):
        """Test case for update_connector

        Update a connector  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
