# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from models.connector_content_search_context_schema import ConnectorContentSearchContextSchema  # noqa: E501
from rustici_engine.rest import ApiException


class TestConnectorContentSearchContextSchema(unittest.TestCase):
    """ConnectorContentSearchContextSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectorContentSearchContextSchema(self):
        """Test ConnectorContentSearchContextSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rustici_engine.models.connector_content_search_context_schema.ConnectorContentSearchContextSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
