# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from models.connector_list_schema import ConnectorListSchema  # noqa: E501
from rustici_engine.rest import ApiException


class TestConnectorListSchema(unittest.TestCase):
    """ConnectorListSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectorListSchema(self):
        """Test ConnectorListSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rustici_engine.models.connector_list_schema.ConnectorListSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
