# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.app_management_api import AppManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAppManagementApi(unittest.TestCase):
    """AppManagementApi unit test stubs"""

    def setUp(self):
        self.api = api.app_management_api.AppManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_credential(self):
        """Test case for create_credential

        Create credential  # noqa: E501
        """
        pass

    def test_create_or_update_tenant(self):
        """Test case for create_or_update_tenant

        Create or update tenant  # noqa: E501
        """
        pass

    def test_create_token(self):
        """Test case for create_token

        Create token  # noqa: E501
        """
        pass

    def test_delete_application_configuration_setting(self):
        """Test case for delete_application_configuration_setting

        Clears the `settingId` value for this level  # noqa: E501
        """
        pass

    def test_delete_credential(self):
        """Test case for delete_credential

        Removes `credentialId` credentials  # noqa: E501
        """
        pass

    def test_delete_tenant(self):
        """Test case for delete_tenant

        Delete a tenant. Warning: If tenant data is not deleted first, this will leave orphaned rows that can only be deleted manually. Does not remove any data, but does remove mapping between name and key used to store data. Consider deactivating instead.  # noqa: E501
        """
        pass

    def test_delete_tenant_data(self):
        """Test case for delete_tenant_data

        Delete all of a tenant's data.  # noqa: E501
        """
        pass

    def test_get_application_configuration(self):
        """Test case for get_application_configuration

        Returns all configuration settings for this level  # noqa: E501
        """
        pass

    def test_get_authenticated_credential(self):
        """Test case for get_authenticated_credential

        Get information about the credential used to authenticate this request.  # noqa: E501
        """
        pass

    def test_get_credential(self):
        """Test case for get_credential

        Get information on `credentialId` credential  # noqa: E501
        """
        pass

    def test_get_credentials(self):
        """Test case for get_credentials

        List of credentials  # noqa: E501
        """
        pass

    def test_get_pii_deletion_job(self):
        """Test case for get_pii_deletion_job

        Check the status of a PII deletion job with the provided job id.  # noqa: E501
        """
        pass

    def test_get_tenant_list(self):
        """Test case for get_tenant_list

        Get list of all tenants  # noqa: E501
        """
        pass

    def test_inspect_token(self):
        """Test case for inspect_token

        Inspect token  # noqa: E501
        """
        pass

    def test_post_pii_deletion_job(self):
        """Test case for post_pii_deletion_job

        Initiate a job to delete a user's Personal Identifying Information from the system.  # noqa: E501
        """
        pass

    def test_post_update_encrypted_setting(self):
        """Test case for post_update_encrypted_setting

        Re-write settings, and statement pipe passwords using the current encryption settings. For password rotation.  # noqa: E501
        """
        pass

    def test_reset_credential_secret(self):
        """Test case for reset_credential_secret

        Reset credential secret  # noqa: E501
        """
        pass

    def test_set_application_configuration(self):
        """Test case for set_application_configuration

        Set configuration settings for this level.  # noqa: E501
        """
        pass

    def test_update_credential(self):
        """Test case for update_credential

        Update `credentialId` credentials  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
