# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from models.media_file_metadata_schema import MediaFileMetadataSchema  # noqa: E501
from rustici_engine.rest import ApiException


class TestMediaFileMetadataSchema(unittest.TestCase):
    """MediaFileMetadataSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMediaFileMetadataSchema(self):
        """Test MediaFileMetadataSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rustici_engine.models.media_file_metadata_schema.MediaFileMetadataSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
