# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.xapi_credential_put_schema import XapiCredentialPutSchema  # noqa: E501
from swagger_client.rest import ApiException


class TestXapiCredentialPutSchema(unittest.TestCase):
    """XapiCredentialPutSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testXapiCredentialPutSchema(self):
        """Test XapiCredentialPutSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.xapi_credential_put_schema.XapiCredentialPutSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
