# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.dispatch_lti_info_schema import DispatchLtiInfoSchema  # noqa: E501
from swagger_client.rest import ApiException


class TestDispatchLtiInfoSchema(unittest.TestCase):
    """DispatchLtiInfoSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDispatchLtiInfoSchema(self):
        """Test DispatchLtiInfoSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.dispatch_lti_info_schema.DispatchLtiInfoSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
