# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from models.credential_created_schema import CredentialCreatedSchema  # noqa: E501
from rustici_engine.rest import ApiException


class TestCredentialCreatedSchema(unittest.TestCase):
    """CredentialCreatedSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCredentialCreatedSchema(self):
        """Test CredentialCreatedSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = rustici_engine.models.credential_created_schema.CredentialCreatedSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
