# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.runtime_interaction_schema import RuntimeInteractionSchema  # noqa: E501
from swagger_client.rest import ApiException


class TestRuntimeInteractionSchema(unittest.TestCase):
    """RuntimeInteractionSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuntimeInteractionSchema(self):
        """Test RuntimeInteractionSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.runtime_interaction_schema.RuntimeInteractionSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
