# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import rustici_engine
from api.registration_api import RegistrationApi  # noqa: E501
from rustici_engine.rest import ApiException


class TestRegistrationApi(unittest.TestCase):
    """RegistrationApi unit test stubs"""

    def setUp(self):
        self.api = api.registration_api.RegistrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_build_registration_launch_link(self):
        """Test case for build_registration_launch_link

        Returns the link to use to launch this registration  # noqa: E501
        """
        pass

    def test_create_new_registration_instance(self):
        """Test case for create_new_registration_instance

        Create a new instance for this registration specified by the registration ID  # noqa: E501
        """
        pass

    def test_create_registration(self):
        """Test case for create_registration

        Create a registration.  # noqa: E501
        """
        pass

    def test_delete_registration(self):
        """Test case for delete_registration

        Delete `registrationId`  # noqa: E501
        """
        pass

    def test_delete_registration_configuration_setting(self):
        """Test case for delete_registration_configuration_setting

        Clears the `settingId` value for this registration  # noqa: E501
        """
        pass

    def test_delete_registration_global_data(self):
        """Test case for delete_registration_global_data

        delete global data associated with `registrationId`  # noqa: E501
        """
        pass

    def test_delete_registration_instance(self):
        """Test case for delete_registration_instance

        Delete instance `instanceId` of `registrationId`  # noqa: E501
        """
        pass

    def test_delete_registration_instance_configuration_setting(self):
        """Test case for delete_registration_instance_configuration_setting

        Clears the `settingId` value for this registration instance  # noqa: E501
        """
        pass

    def test_delete_registration_progress(self):
        """Test case for delete_registration_progress

        delete registration progress (clear registration)  # noqa: E501
        """
        pass

    def test_get_registration(self):
        """Test case for get_registration

        Does this registration exist?  # noqa: E501
        """
        pass

    def test_get_registration_configuration(self):
        """Test case for get_registration_configuration

        Returns all configuration settings for this registration  # noqa: E501
        """
        pass

    def test_get_registration_instance_configuration(self):
        """Test case for get_registration_instance_configuration

        Returns all configuration settings for this registration instance  # noqa: E501
        """
        pass

    def test_get_registration_instance_launch_history(self):
        """Test case for get_registration_instance_launch_history

        Returns history of this registration's launches  # noqa: E501
        """
        pass

    def test_get_registration_instance_progress(self):
        """Test case for get_registration_instance_progress

        Get registration progress for instance `instanceId` of `registrationId`  # noqa: E501
        """
        pass

    def test_get_registration_instance_statements(self):
        """Test case for get_registration_instance_statements

        Get xAPI statements for instance `instanceId` of `registrationId`  # noqa: E501
        """
        pass

    def test_get_registration_instances(self):
        """Test case for get_registration_instances

        Get all the instances of this the registration specified by the registration ID  # noqa: E501
        """
        pass

    def test_get_registration_launch_history(self):
        """Test case for get_registration_launch_history

        Returns history of this registration's launches  # noqa: E501
        """
        pass

    def test_get_registration_progress(self):
        """Test case for get_registration_progress

        Get registration progress for `registrationId`  # noqa: E501
        """
        pass

    def test_get_registration_statements(self):
        """Test case for get_registration_statements

        Get xAPI statements for `registrationId`  # noqa: E501
        """
        pass

    def test_get_registrations(self):
        """Test case for get_registrations

        Gets a list of registrations including a summary of the status of each registration.  # noqa: E501
        """
        pass

    def test_set_registration_configuration(self):
        """Test case for set_registration_configuration

        Set configuration settings for this registration.  # noqa: E501
        """
        pass

    def test_set_registration_instance_configuration(self):
        """Test case for set_registration_instance_configuration

        Set configuration settings for this registration instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
