# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.xapi_context_activity import XapiContextActivity  # noqa: E501
from swagger_client.rest import ApiException


class TestXapiContextActivity(unittest.TestCase):
    """XapiContextActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testXapiContextActivity(self):
        """Test XapiContextActivity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.xapi_context_activity.XapiContextActivity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
