# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class LaunchPageResponseSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'launch_url': 'str'
    }

    attribute_map = {
        'launch_url': 'launchUrl'
    }

    def __init__(self, launch_url=None):  # noqa: E501
        """LaunchPageResponseSchema - a model defined in Swagger"""  # noqa: E501
        self._launch_url = None
        self.discriminator = None
        self.launch_url = launch_url

    @property
    def launch_url(self):
        """Gets the launch_url of this LaunchPageResponseSchema.  # noqa: E501

        The Engine launch URL for the dispatch registration, or null if there was an error.  # noqa: E501

        :return: The launch_url of this LaunchPageResponseSchema.  # noqa: E501
        :rtype: str
        """
        return self._launch_url

    @launch_url.setter
    def launch_url(self, launch_url):
        """Sets the launch_url of this LaunchPageResponseSchema.

        The Engine launch URL for the dispatch registration, or null if there was an error.  # noqa: E501

        :param launch_url: The launch_url of this LaunchPageResponseSchema.  # noqa: E501
        :type: str
        """
        if launch_url is None:
            raise ValueError("Invalid value for `launch_url`, must not be `None`")  # noqa: E501

        self._launch_url = launch_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LaunchPageResponseSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LaunchPageResponseSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
