# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class UserCountDetailSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tenant_name': 'str',
        'total': 'int',
        'dispatched': 'int',
        'non_dispatched': 'int'
    }

    attribute_map = {
        'tenant_name': 'tenantName',
        'total': 'total',
        'dispatched': 'dispatched',
        'non_dispatched': 'nonDispatched'
    }

    def __init__(self, tenant_name=None, total=None, dispatched=None, non_dispatched=None):  # noqa: E501
        """UserCountDetailSchema - a model defined in Swagger"""  # noqa: E501
        self._tenant_name = None
        self._total = None
        self._dispatched = None
        self._non_dispatched = None
        self.discriminator = None
        if tenant_name is not None:
            self.tenant_name = tenant_name
        self.total = total
        if dispatched is not None:
            self.dispatched = dispatched
        if non_dispatched is not None:
            self.non_dispatched = non_dispatched

    @property
    def tenant_name(self):
        """Gets the tenant_name of this UserCountDetailSchema.  # noqa: E501


        :return: The tenant_name of this UserCountDetailSchema.  # noqa: E501
        :rtype: str
        """
        return self._tenant_name

    @tenant_name.setter
    def tenant_name(self, tenant_name):
        """Sets the tenant_name of this UserCountDetailSchema.


        :param tenant_name: The tenant_name of this UserCountDetailSchema.  # noqa: E501
        :type: str
        """

        self._tenant_name = tenant_name

    @property
    def total(self):
        """Gets the total of this UserCountDetailSchema.  # noqa: E501


        :return: The total of this UserCountDetailSchema.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this UserCountDetailSchema.


        :param total: The total of this UserCountDetailSchema.  # noqa: E501
        :type: int
        """
        if total is None:
            raise ValueError("Invalid value for `total`, must not be `None`")  # noqa: E501

        self._total = total

    @property
    def dispatched(self):
        """Gets the dispatched of this UserCountDetailSchema.  # noqa: E501


        :return: The dispatched of this UserCountDetailSchema.  # noqa: E501
        :rtype: int
        """
        return self._dispatched

    @dispatched.setter
    def dispatched(self, dispatched):
        """Sets the dispatched of this UserCountDetailSchema.


        :param dispatched: The dispatched of this UserCountDetailSchema.  # noqa: E501
        :type: int
        """

        self._dispatched = dispatched

    @property
    def non_dispatched(self):
        """Gets the non_dispatched of this UserCountDetailSchema.  # noqa: E501


        :return: The non_dispatched of this UserCountDetailSchema.  # noqa: E501
        :rtype: int
        """
        return self._non_dispatched

    @non_dispatched.setter
    def non_dispatched(self, non_dispatched):
        """Sets the non_dispatched of this UserCountDetailSchema.


        :param non_dispatched: The non_dispatched of this UserCountDetailSchema.  # noqa: E501
        :type: int
        """

        self._non_dispatched = non_dispatched

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserCountDetailSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserCountDetailSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
