# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class OAuthCredentialsSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'consumer_key': 'str',
        'shared_secret': 'str'
    }

    attribute_map = {
        'consumer_key': 'consumerKey',
        'shared_secret': 'sharedSecret'
    }

    def __init__(self, consumer_key=None, shared_secret=None):  # noqa: E501
        """OAuthCredentialsSchema - a model defined in Swagger"""  # noqa: E501
        self._consumer_key = None
        self._shared_secret = None
        self.discriminator = None
        self.consumer_key = consumer_key
        self.shared_secret = shared_secret

    @property
    def consumer_key(self):
        """Gets the consumer_key of this OAuthCredentialsSchema.  # noqa: E501

        the OAuth consumer key  # noqa: E501

        :return: The consumer_key of this OAuthCredentialsSchema.  # noqa: E501
        :rtype: str
        """
        return self._consumer_key

    @consumer_key.setter
    def consumer_key(self, consumer_key):
        """Sets the consumer_key of this OAuthCredentialsSchema.

        the OAuth consumer key  # noqa: E501

        :param consumer_key: The consumer_key of this OAuthCredentialsSchema.  # noqa: E501
        :type: str
        """
        if consumer_key is None:
            raise ValueError("Invalid value for `consumer_key`, must not be `None`")  # noqa: E501

        self._consumer_key = consumer_key

    @property
    def shared_secret(self):
        """Gets the shared_secret of this OAuthCredentialsSchema.  # noqa: E501

        the OAuth shared secret  # noqa: E501

        :return: The shared_secret of this OAuthCredentialsSchema.  # noqa: E501
        :rtype: str
        """
        return self._shared_secret

    @shared_secret.setter
    def shared_secret(self, shared_secret):
        """Sets the shared_secret of this OAuthCredentialsSchema.

        the OAuth shared secret  # noqa: E501

        :param shared_secret: The shared_secret of this OAuthCredentialsSchema.  # noqa: E501
        :type: str
        """
        if shared_secret is None:
            raise ValueError("Invalid value for `shared_secret`, must not be `None`")  # noqa: E501

        self._shared_secret = shared_secret

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OAuthCredentialsSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OAuthCredentialsSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
