# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PluginVersionSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'plugin': 'str',
        'engine': 'str'
    }

    attribute_map = {
        'plugin': 'plugin',
        'engine': 'engine'
    }

    def __init__(self, plugin=None, engine=None):  # noqa: E501
        """PluginVersionSchema - a model defined in Swagger"""  # noqa: E501
        self._plugin = None
        self._engine = None
        self.discriminator = None
        if plugin is not None:
            self.plugin = plugin
        if engine is not None:
            self.engine = engine

    @property
    def plugin(self):
        """Gets the plugin of this PluginVersionSchema.  # noqa: E501

        version of this plugin  # noqa: E501

        :return: The plugin of this PluginVersionSchema.  # noqa: E501
        :rtype: str
        """
        return self._plugin

    @plugin.setter
    def plugin(self, plugin):
        """Sets the plugin of this PluginVersionSchema.

        version of this plugin  # noqa: E501

        :param plugin: The plugin of this PluginVersionSchema.  # noqa: E501
        :type: str
        """

        self._plugin = plugin

    @property
    def engine(self):
        """Gets the engine of this PluginVersionSchema.  # noqa: E501

        the version of Engine with which this plugin was built  # noqa: E501

        :return: The engine of this PluginVersionSchema.  # noqa: E501
        :rtype: str
        """
        return self._engine

    @engine.setter
    def engine(self, engine):
        """Sets the engine of this PluginVersionSchema.

        the version of Engine with which this plugin was built  # noqa: E501

        :param engine: The engine of this PluginVersionSchema.  # noqa: E501
        :type: str
        """

        self._engine = engine

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PluginVersionSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PluginVersionSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
