# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TokenInfoSchema(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'permissions': 'PermissionsSchema',
        'expiry': 'datetime',
        'additional_values': 'list[ItemValuePairSchema]'
    }

    attribute_map = {
        'permissions': 'permissions',
        'expiry': 'expiry',
        'additional_values': 'additionalValues'
    }

    def __init__(self, permissions=None, expiry=None, additional_values=None):  # noqa: E501
        """TokenInfoSchema - a model defined in Swagger"""  # noqa: E501
        self._permissions = None
        self._expiry = None
        self._additional_values = None
        self.discriminator = None
        if permissions is not None:
            self.permissions = permissions
        if expiry is not None:
            self.expiry = expiry
        if additional_values is not None:
            self.additional_values = additional_values

    @property
    def permissions(self):
        """Gets the permissions of this TokenInfoSchema.  # noqa: E501


        :return: The permissions of this TokenInfoSchema.  # noqa: E501
        :rtype: PermissionsSchema
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this TokenInfoSchema.


        :param permissions: The permissions of this TokenInfoSchema.  # noqa: E501
        :type: PermissionsSchema
        """

        self._permissions = permissions

    @property
    def expiry(self):
        """Gets the expiry of this TokenInfoSchema.  # noqa: E501

        Expiration of the token.  # noqa: E501

        :return: The expiry of this TokenInfoSchema.  # noqa: E501
        :rtype: datetime
        """
        return self._expiry

    @expiry.setter
    def expiry(self, expiry):
        """Sets the expiry of this TokenInfoSchema.

        Expiration of the token.  # noqa: E501

        :param expiry: The expiry of this TokenInfoSchema.  # noqa: E501
        :type: datetime
        """

        self._expiry = expiry

    @property
    def additional_values(self):
        """Gets the additional_values of this TokenInfoSchema.  # noqa: E501

        Additional values that were included in the token  # noqa: E501

        :return: The additional_values of this TokenInfoSchema.  # noqa: E501
        :rtype: list[ItemValuePairSchema]
        """
        return self._additional_values

    @additional_values.setter
    def additional_values(self, additional_values):
        """Sets the additional_values of this TokenInfoSchema.

        Additional values that were included in the token  # noqa: E501

        :param additional_values: The additional_values of this TokenInfoSchema.  # noqa: E501
        :type: list[ItemValuePairSchema]
        """

        self._additional_values = additional_values

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TokenInfoSchema, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenInfoSchema):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
