# coding: utf-8

"""
    Rustici Engine API

    Rustici Engine API  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from rustici_engine.api_client import ApiClient


class XapiApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_statement_pipe(self, body, engine_tenant_name, **kwargs):  # noqa: E501
        """Create an xAPI statement pipe.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_statement_pipe(body, engine_tenant_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param XapiStatementPipePostSchema body: (required)
        :param str engine_tenant_name: tenant for this request (required)
        :return: StringResultSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_statement_pipe_with_http_info(body, engine_tenant_name, **kwargs)  # noqa: E501
        else:
            (data) = self.create_statement_pipe_with_http_info(body, engine_tenant_name, **kwargs)  # noqa: E501
            return data

    def create_statement_pipe_with_http_info(self, body, engine_tenant_name, **kwargs):  # noqa: E501
        """Create an xAPI statement pipe.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_statement_pipe_with_http_info(body, engine_tenant_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param XapiStatementPipePostSchema body: (required)
        :param str engine_tenant_name: tenant for this request (required)
        :return: StringResultSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'engine_tenant_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_statement_pipe" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `create_statement_pipe`")  # noqa: E501
        # verify the required parameter 'engine_tenant_name' is set
        if ('engine_tenant_name' not in params or
                params['engine_tenant_name'] is None):
            raise ValueError("Missing the required parameter `engine_tenant_name` when calling `create_statement_pipe`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'engine_tenant_name' in params:
            header_params['engineTenantName'] = params['engine_tenant_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic', 'oauth']  # noqa: E501

        return self.api_client.call_api(
            '/xapi/statementPipes', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StringResultSchema',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_xapi_credential(self, body, engine_tenant_name, **kwargs):  # noqa: E501
        """Create an xAPI credential  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_xapi_credential(body, engine_tenant_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param XapiCredentialPostSchema body: (required)
        :param str engine_tenant_name: tenant for this request (required)
        :return: StringResultSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_xapi_credential_with_http_info(body, engine_tenant_name, **kwargs)  # noqa: E501
        else:
            (data) = self.create_xapi_credential_with_http_info(body, engine_tenant_name, **kwargs)  # noqa: E501
            return data

    def create_xapi_credential_with_http_info(self, body, engine_tenant_name, **kwargs):  # noqa: E501
        """Create an xAPI credential  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_xapi_credential_with_http_info(body, engine_tenant_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param XapiCredentialPostSchema body: (required)
        :param str engine_tenant_name: tenant for this request (required)
        :return: StringResultSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'engine_tenant_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_xapi_credential" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `create_xapi_credential`")  # noqa: E501
        # verify the required parameter 'engine_tenant_name' is set
        if ('engine_tenant_name' not in params or
                params['engine_tenant_name'] is None):
            raise ValueError("Missing the required parameter `engine_tenant_name` when calling `create_xapi_credential`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'engine_tenant_name' in params:
            header_params['engineTenantName'] = params['engine_tenant_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic', 'oauth']  # noqa: E501

        return self.api_client.call_api(
            '/xapi/credentials', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='StringResultSchema',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_statement_pipe(self, engine_tenant_name, statement_pipe_id, **kwargs):  # noqa: E501
        """Deletes the xAPI statement pipe specified with the id `statementPipeId`  # noqa: E501

        Caution: avoid re-creating a statement pipe with the same ID quickly after a delete. The old version could still be processing, in which case the new pipe could be updated improperly by the processor.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_statement_pipe(engine_tenant_name, statement_pipe_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str engine_tenant_name: tenant for this request (required)
        :param str statement_pipe_id: id for this xAPI statement pipe (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_statement_pipe_with_http_info(engine_tenant_name, statement_pipe_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_statement_pipe_with_http_info(engine_tenant_name, statement_pipe_id, **kwargs)  # noqa: E501
            return data

    def delete_statement_pipe_with_http_info(self, engine_tenant_name, statement_pipe_id, **kwargs):  # noqa: E501
        """Deletes the xAPI statement pipe specified with the id `statementPipeId`  # noqa: E501

        Caution: avoid re-creating a statement pipe with the same ID quickly after a delete. The old version could still be processing, in which case the new pipe could be updated improperly by the processor.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_statement_pipe_with_http_info(engine_tenant_name, statement_pipe_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str engine_tenant_name: tenant for this request (required)
        :param str statement_pipe_id: id for this xAPI statement pipe (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['engine_tenant_name', 'statement_pipe_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_statement_pipe" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'engine_tenant_name' is set
        if ('engine_tenant_name' not in params or
                params['engine_tenant_name'] is None):
            raise ValueError("Missing the required parameter `engine_tenant_name` when calling `delete_statement_pipe`")  # noqa: E501
        # verify the required parameter 'statement_pipe_id' is set
        if ('statement_pipe_id' not in params or
                params['statement_pipe_id'] is None):
            raise ValueError("Missing the required parameter `statement_pipe_id` when calling `delete_statement_pipe`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'statement_pipe_id' in params:
            path_params['statementPipeId'] = params['statement_pipe_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'engine_tenant_name' in params:
            header_params['engineTenantName'] = params['engine_tenant_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic', 'oauth']  # noqa: E501

        return self.api_client.call_api(
            '/xapi/statementPipes/{statementPipeId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_xapi_credential(self, engine_tenant_name, xapi_credential_id, **kwargs):  # noqa: E501
        """Deletes the xAPI credential specified with the id `xapiCredentialId`  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_xapi_credential(engine_tenant_name, xapi_credential_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str engine_tenant_name: tenant for this request (required)
        :param str xapi_credential_id: id for this xAPI credential (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_xapi_credential_with_http_info(engine_tenant_name, xapi_credential_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_xapi_credential_with_http_info(engine_tenant_name, xapi_credential_id, **kwargs)  # noqa: E501
            return data

    def delete_xapi_credential_with_http_info(self, engine_tenant_name, xapi_credential_id, **kwargs):  # noqa: E501
        """Deletes the xAPI credential specified with the id `xapiCredentialId`  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_xapi_credential_with_http_info(engine_tenant_name, xapi_credential_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str engine_tenant_name: tenant for this request (required)
        :param str xapi_credential_id: id for this xAPI credential (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['engine_tenant_name', 'xapi_credential_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_xapi_credential" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'engine_tenant_name' is set
        if ('engine_tenant_name' not in params or
                params['engine_tenant_name'] is None):
            raise ValueError("Missing the required parameter `engine_tenant_name` when calling `delete_xapi_credential`")  # noqa: E501
        # verify the required parameter 'xapi_credential_id' is set
        if ('xapi_credential_id' not in params or
                params['xapi_credential_id'] is None):
            raise ValueError("Missing the required parameter `xapi_credential_id` when calling `delete_xapi_credential`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'xapi_credential_id' in params:
            path_params['xapiCredentialId'] = params['xapi_credential_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'engine_tenant_name' in params:
            header_params['engineTenantName'] = params['engine_tenant_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic', 'oauth']  # noqa: E501

        return self.api_client.call_api(
            '/xapi/credentials/{xapiCredentialId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_statement_pipe(self, engine_tenant_name, statement_pipe_id, **kwargs):  # noqa: E501
        """Retrieves xAPI statement pipe specified by id `statementPipeId.`  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_statement_pipe(engine_tenant_name, statement_pipe_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str engine_tenant_name: tenant for this request (required)
        :param str statement_pipe_id: id for this xAPI statement pipe (required)
        :return: XapiStatementPipeSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_statement_pipe_with_http_info(engine_tenant_name, statement_pipe_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_statement_pipe_with_http_info(engine_tenant_name, statement_pipe_id, **kwargs)  # noqa: E501
            return data

    def get_statement_pipe_with_http_info(self, engine_tenant_name, statement_pipe_id, **kwargs):  # noqa: E501
        """Retrieves xAPI statement pipe specified by id `statementPipeId.`  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_statement_pipe_with_http_info(engine_tenant_name, statement_pipe_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str engine_tenant_name: tenant for this request (required)
        :param str statement_pipe_id: id for this xAPI statement pipe (required)
        :return: XapiStatementPipeSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['engine_tenant_name', 'statement_pipe_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_statement_pipe" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'engine_tenant_name' is set
        if ('engine_tenant_name' not in params or
                params['engine_tenant_name'] is None):
            raise ValueError("Missing the required parameter `engine_tenant_name` when calling `get_statement_pipe`")  # noqa: E501
        # verify the required parameter 'statement_pipe_id' is set
        if ('statement_pipe_id' not in params or
                params['statement_pipe_id'] is None):
            raise ValueError("Missing the required parameter `statement_pipe_id` when calling `get_statement_pipe`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'statement_pipe_id' in params:
            path_params['statementPipeId'] = params['statement_pipe_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'engine_tenant_name' in params:
            header_params['engineTenantName'] = params['engine_tenant_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic', 'oauth']  # noqa: E501

        return self.api_client.call_api(
            '/xapi/statementPipes/{statementPipeId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='XapiStatementPipeSchema',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_statement_pipes(self, engine_tenant_name, **kwargs):  # noqa: E501
        """Get a list of all xAPI statement pipes  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_statement_pipes(engine_tenant_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str engine_tenant_name: tenant for this request (required)
        :return: XapiStatementPipeListSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_statement_pipes_with_http_info(engine_tenant_name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_statement_pipes_with_http_info(engine_tenant_name, **kwargs)  # noqa: E501
            return data

    def get_statement_pipes_with_http_info(self, engine_tenant_name, **kwargs):  # noqa: E501
        """Get a list of all xAPI statement pipes  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_statement_pipes_with_http_info(engine_tenant_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str engine_tenant_name: tenant for this request (required)
        :return: XapiStatementPipeListSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['engine_tenant_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_statement_pipes" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'engine_tenant_name' is set
        if ('engine_tenant_name' not in params or
                params['engine_tenant_name'] is None):
            raise ValueError("Missing the required parameter `engine_tenant_name` when calling `get_statement_pipes`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'engine_tenant_name' in params:
            header_params['engineTenantName'] = params['engine_tenant_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic', 'oauth']  # noqa: E501

        return self.api_client.call_api(
            '/xapi/statementPipes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='XapiStatementPipeListSchema',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_xapi_credential(self, engine_tenant_name, xapi_credential_id, **kwargs):  # noqa: E501
        """Retrieves the xAPI credential specified by id `xapiCredentialId`  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_xapi_credential(engine_tenant_name, xapi_credential_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str engine_tenant_name: tenant for this request (required)
        :param str xapi_credential_id: id for this xAPI credential (required)
        :return: XapiCredentialSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_xapi_credential_with_http_info(engine_tenant_name, xapi_credential_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_xapi_credential_with_http_info(engine_tenant_name, xapi_credential_id, **kwargs)  # noqa: E501
            return data

    def get_xapi_credential_with_http_info(self, engine_tenant_name, xapi_credential_id, **kwargs):  # noqa: E501
        """Retrieves the xAPI credential specified by id `xapiCredentialId`  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_xapi_credential_with_http_info(engine_tenant_name, xapi_credential_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str engine_tenant_name: tenant for this request (required)
        :param str xapi_credential_id: id for this xAPI credential (required)
        :return: XapiCredentialSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['engine_tenant_name', 'xapi_credential_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_xapi_credential" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'engine_tenant_name' is set
        if ('engine_tenant_name' not in params or
                params['engine_tenant_name'] is None):
            raise ValueError("Missing the required parameter `engine_tenant_name` when calling `get_xapi_credential`")  # noqa: E501
        # verify the required parameter 'xapi_credential_id' is set
        if ('xapi_credential_id' not in params or
                params['xapi_credential_id'] is None):
            raise ValueError("Missing the required parameter `xapi_credential_id` when calling `get_xapi_credential`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'xapi_credential_id' in params:
            path_params['xapiCredentialId'] = params['xapi_credential_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'engine_tenant_name' in params:
            header_params['engineTenantName'] = params['engine_tenant_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic', 'oauth']  # noqa: E501

        return self.api_client.call_api(
            '/xapi/credentials/{xapiCredentialId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='XapiCredentialSchema',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_xapi_credentials(self, engine_tenant_name, **kwargs):  # noqa: E501
        """Get a list of all xAPI credentials  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_xapi_credentials(engine_tenant_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str engine_tenant_name: tenant for this request (required)
        :param str more: Value for this parameter will be provided in the 'more' property of lists, where needed. An opaque value, construction and parsing may change without notice.
        :return: XapiCredentialsListSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_xapi_credentials_with_http_info(engine_tenant_name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_xapi_credentials_with_http_info(engine_tenant_name, **kwargs)  # noqa: E501
            return data

    def get_xapi_credentials_with_http_info(self, engine_tenant_name, **kwargs):  # noqa: E501
        """Get a list of all xAPI credentials  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_xapi_credentials_with_http_info(engine_tenant_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str engine_tenant_name: tenant for this request (required)
        :param str more: Value for this parameter will be provided in the 'more' property of lists, where needed. An opaque value, construction and parsing may change without notice.
        :return: XapiCredentialsListSchema
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['engine_tenant_name', 'more']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_xapi_credentials" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'engine_tenant_name' is set
        if ('engine_tenant_name' not in params or
                params['engine_tenant_name'] is None):
            raise ValueError("Missing the required parameter `engine_tenant_name` when calling `get_xapi_credentials`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'more' in params:
            query_params.append(('more', params['more']))  # noqa: E501

        header_params = {}
        if 'engine_tenant_name' in params:
            header_params['engineTenantName'] = params['engine_tenant_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic', 'oauth']  # noqa: E501

        return self.api_client.call_api(
            '/xapi/credentials', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='XapiCredentialsListSchema',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def set_statement_pipe(self, body, engine_tenant_name, statement_pipe_id, **kwargs):  # noqa: E501
        """Either edits an existing xAPI statement pipe or creates a new one, specified by id `statementPipeId`  # noqa: E501

        Editing a statement pipe will cause it to start over and forward any statements it finds, even if the prior version of the pipe had already forwarded those statements. If the statement pipe being edited is currently being processed, the this request will fail with a status code of 409.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.set_statement_pipe(body, engine_tenant_name, statement_pipe_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param XapiStatementPipePutSchema body: (required)
        :param str engine_tenant_name: tenant for this request (required)
        :param str statement_pipe_id: id for this xAPI statement pipe (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.set_statement_pipe_with_http_info(body, engine_tenant_name, statement_pipe_id, **kwargs)  # noqa: E501
        else:
            (data) = self.set_statement_pipe_with_http_info(body, engine_tenant_name, statement_pipe_id, **kwargs)  # noqa: E501
            return data

    def set_statement_pipe_with_http_info(self, body, engine_tenant_name, statement_pipe_id, **kwargs):  # noqa: E501
        """Either edits an existing xAPI statement pipe or creates a new one, specified by id `statementPipeId`  # noqa: E501

        Editing a statement pipe will cause it to start over and forward any statements it finds, even if the prior version of the pipe had already forwarded those statements. If the statement pipe being edited is currently being processed, the this request will fail with a status code of 409.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.set_statement_pipe_with_http_info(body, engine_tenant_name, statement_pipe_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param XapiStatementPipePutSchema body: (required)
        :param str engine_tenant_name: tenant for this request (required)
        :param str statement_pipe_id: id for this xAPI statement pipe (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'engine_tenant_name', 'statement_pipe_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method set_statement_pipe" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `set_statement_pipe`")  # noqa: E501
        # verify the required parameter 'engine_tenant_name' is set
        if ('engine_tenant_name' not in params or
                params['engine_tenant_name'] is None):
            raise ValueError("Missing the required parameter `engine_tenant_name` when calling `set_statement_pipe`")  # noqa: E501
        # verify the required parameter 'statement_pipe_id' is set
        if ('statement_pipe_id' not in params or
                params['statement_pipe_id'] is None):
            raise ValueError("Missing the required parameter `statement_pipe_id` when calling `set_statement_pipe`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'statement_pipe_id' in params:
            path_params['statementPipeId'] = params['statement_pipe_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'engine_tenant_name' in params:
            header_params['engineTenantName'] = params['engine_tenant_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic', 'oauth']  # noqa: E501

        return self.api_client.call_api(
            '/xapi/statementPipes/{statementPipeId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def set_xapi_credential(self, body, engine_tenant_name, xapi_credential_id, **kwargs):  # noqa: E501
        """Either edits an existing xAPI credential or creates a new one, specified by id `xapiCredentialId`  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.set_xapi_credential(body, engine_tenant_name, xapi_credential_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param XapiCredentialPutSchema body: (required)
        :param str engine_tenant_name: tenant for this request (required)
        :param str xapi_credential_id: id for this xAPI credential (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.set_xapi_credential_with_http_info(body, engine_tenant_name, xapi_credential_id, **kwargs)  # noqa: E501
        else:
            (data) = self.set_xapi_credential_with_http_info(body, engine_tenant_name, xapi_credential_id, **kwargs)  # noqa: E501
            return data

    def set_xapi_credential_with_http_info(self, body, engine_tenant_name, xapi_credential_id, **kwargs):  # noqa: E501
        """Either edits an existing xAPI credential or creates a new one, specified by id `xapiCredentialId`  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.set_xapi_credential_with_http_info(body, engine_tenant_name, xapi_credential_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param XapiCredentialPutSchema body: (required)
        :param str engine_tenant_name: tenant for this request (required)
        :param str xapi_credential_id: id for this xAPI credential (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'engine_tenant_name', 'xapi_credential_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method set_xapi_credential" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `set_xapi_credential`")  # noqa: E501
        # verify the required parameter 'engine_tenant_name' is set
        if ('engine_tenant_name' not in params or
                params['engine_tenant_name'] is None):
            raise ValueError("Missing the required parameter `engine_tenant_name` when calling `set_xapi_credential`")  # noqa: E501
        # verify the required parameter 'xapi_credential_id' is set
        if ('xapi_credential_id' not in params or
                params['xapi_credential_id'] is None):
            raise ValueError("Missing the required parameter `xapi_credential_id` when calling `set_xapi_credential`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'xapi_credential_id' in params:
            path_params['xapiCredentialId'] = params['xapi_credential_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'engine_tenant_name' in params:
            header_params['engineTenantName'] = params['engine_tenant_name']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['basic', 'oauth']  # noqa: E501

        return self.api_client.call_api(
            '/xapi/credentials/{xapiCredentialId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
